# Service name and port
spring.application.name=ConfigServer
server.port=8888

# GitHub repo
spring.cloud.config.server.git.uri=https://github.com/Davidemad24/ArtAuction
spring.cloud.config.server.git.username=Davidemad24
spring.cloud.config.server.git.password=${CONFIG_REPO_GIT_PASSWORD:CHANGE_ME}
spring.cloud.config.server.git.default-label=main
