export const APP_ROUTES = {
  HOME: '/',
  ARTWORKS: '/artworks',
  ARTWORK_DETAIL: '/artworks/:artworkId',
  AUTH_LOGIN: '/auth/login',
  AUTH_BUYER_REGISTER: '/auth/register/buyer',
  AUTH_ARTIST_REGISTER: '/auth/register/artist',
  ARTIST_PENDING: '/artist/pending-approval',
  BUYER_WATCHLIST: '/buyer/watchlist',
  BUYER_BIDS: '/buyer/my-bids',
  BUYER_NOTIFICATIONS: '/buyer/notifications',
  BUYER_PURCHASES: '/buyer/purchases',
  BUYER_PAYMENT: '/buyer/payment/:notificationId',
  ARTIST_DASHBOARD: '/artist/dashboard',
  ARTIST_ARTWORKS: '/artist/artworks',
  ARTIST_ARTWORK_NEW: '/artist/artworks/new',
  ARTIST_ARTWORK_EDIT: '/artist/artworks/:artworkId/edit',
  ARTIST_AUCTION_EXTENSION: '/artist/auction-extension',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PENDING_ARTISTS: '/admin/pending-artists',
  ADMIN_PENDING_ARTWORKS: '/admin/pending-artworks',
  ADMIN_ACCEPTED_ARTISTS: '/admin/accepted-artists',
  UNAUTHORIZED: '/unauthorized',
}
