# Service name and port
spring.application.name=ArtistServices
server.port=8081

# Eureka connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database URL
spring.datasource.url=jdbc:sqlserver://DESKTOP-9RSJN03\\SQLEXPRESS;databaseName=Microservices_ArtAuction;\
  integratedSecurity=true;encrypt=true;trustServerCertificate=true;

# Driver Class
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configurations (must match Authentication Service exactly)
jwt.secret-key=ArtAuction-Super-Secret-Key-Min-32-Chars!!
jwt.issuer=ArtAuction
jwt.audience=ArtAuctionClients
jwt.expiry-hours=1

# Kafka Connection
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.configuration.max.request.size=20971520
spring.cloud.stream.kafka.binder.configuration.max.partition.fetch.bytes=20971520

# Kafka Serialization
spring.cloud.stream.kafka.bindings.checkAdminRequest-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.checkAdminReply-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Bindings
spring.cloud.stream.bindings.checkAdminRequest-out-0.destination=artist.check.admin.request
spring.cloud.stream.bindings.checkAdminReply-in-0.destination=artist.check.admin.reply
spring.cloud.stream.bindings.checkAdminReply-in-0.group=artist-service


# ArtworkPostServices input requests
spring.cloud.stream.bindings.checkArtistRequest-in-0.destination=artworkpost.check.artist.request
spring.cloud.stream.bindings.checkArtistRequest-in-0.group=artist-service

spring.cloud.stream.bindings.artistDataRequest-in-0.destination=artworkpost.artist.data.request
spring.cloud.stream.bindings.artistDataRequest-in-0.group=artist-service

# ArtworkPostServices output replies
spring.cloud.stream.bindings.artistDataRequest-out-0.destination=artworkpost.artist.data.reply
spring.cloud.stream.bindings.checkArtistRequest-out-0.destination=artworkpost.check.artist.reply

# Register Functions
spring.cloud.function.definition=checkArtistRequest;artistDataRequest;checkAdminReply