# Service name and port
spring.application.name=AuthenticationServices
server.port=8084

# Eureka connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database URL
spring.datasource.url=jdbc:sqlserver://DESKTOP-9RSJN03\\SQLEXPRESS;databaseName=Microservices_ArtAuction;\
  integratedSecurity=true;encrypt=true;trustServerCertificate=true

# Driver Class
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT configurations
jwt.secret-key=ArtAuction-Super-Secret-Key-Min-32-Chars!!
jwt.issuer=ArtAuction
jwt.audience=ArtAuctionClients
jwt.expiry-hours=1

# Kafka connections and topics size
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.configuration.max.request.size=10485760

# AuctionServices Input Request
spring.cloud.stream.bindings.checkBuyerRequest-in-0.destination=auction.check.buyer.request
spring.cloud.stream.bindings.checkBuyerRequest-in-0.group=authentication-service
spring.cloud.stream.bindings.buyerDataRequest-in-0.destination=auction.buyer.data.request
spring.cloud.stream.bindings.buyerDataRequest-in-0.group=authentication-service
spring.cloud.stream.bindings.checkAdminRequest-in-0.destination=artworkpost.check.admin.request
spring.cloud.stream.bindings.checkAdminRequest-in-0.group=authentication-service
spring.cloud.stream.bindings.checkBuyerFromPostRequest-in-0.destination=artworkpost.check.buyer.request
spring.cloud.stream.bindings.checkBuyerFromPostRequest-in-0.group=authentication-service
spring.cloud.stream.bindings.checkAdminFromArtistRequest-in-0.destination=artist.check.admin.request
spring.cloud.stream.bindings.checkAdminFromArtistRequest-in-0.group=authentication-service

# AuctionServices Output Reply
spring.cloud.stream.bindings.checkBuyerRequest-out-0.destination=auction.check.buyer.reply
spring.cloud.stream.bindings.buyerDataRequest-out-0.destination=auction.buyer.data.reply
spring.cloud.stream.bindings.checkAdminRequest-out-0.destination=artworkpost.check.admin.reply
spring.cloud.stream.bindings.checkBuyerFromPostRequest-out-0.destination=artworkpost.check.buyer.reply
spring.cloud.stream.bindings.checkAdminFromArtistRequest-out-0.destination=artist.check.admin.reply

# Register functions
spring.cloud.function.definition=buyerDataRequest;checkBuyerRequest;checkAdminRequest;checkBuyerFromPostRequest;\
  checkAdminFromArtistRequest