# Service name and port
spring.application.name=AuctionServices
server.port=8083

# Eureka connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database URL
spring.datasource.url=jdbc:sqlserver://DESKTOP-9RSJN03\\SQLEXPRESS;databaseName=Microservices_ArtAuction;\
  integratedSecurity=true;encrypt=true;trustServerCertificate=true

# Driver Class
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configurations
jwt.secret-key=ArtAuction-Super-Secret-Key-Min-32-Chars!!
jwt.issuer=ArtAuction
jwt.audience=ArtAuctionClients
jwt.expiry-hours=1

# Kafka Connection and topics size
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.configuration.max.request.size=20971520
spring.cloud.stream.kafka.binder.configuration.max.partition.fetch.bytes=20971520

# Kafka serialization
spring.cloud.stream.kafka.bindings.checkBuyerRequest-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.checkBuyerReply-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.cloud.stream.kafka.bindings.checkPostRequest-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.checkPostReply-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.cloud.stream.kafka.bindings.buyerDataRequest-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.buyerDataReply-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.cloud.stream.kafka.bindings.postDataRequest-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.postDataReply-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.cloud.stream.kafka.bindings.sendEmailOut-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.kafka.bindings.endedPostsRequest-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.endedPostsReply-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.cloud.stream.kafka.bindings.updateBuyNowPriceRequest-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.updateBuyNowPriceReply-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.cloud.stream.kafka.bindings.endedPostDataRequest-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.endedPostDataReply-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka binding
spring.cloud.stream.bindings.checkBuyerRequest-out-0.destination=auction.check.buyer.request
spring.cloud.stream.bindings.checkBuyerReply-in-0.destination=auction.check.buyer.reply
spring.cloud.stream.bindings.checkBuyerReply-in-0.group=auction-service

spring.cloud.stream.bindings.checkPostRequest-out-0.destination=auction.check.post.request
spring.cloud.stream.bindings.checkPostReply-in-0.destination=auction.check.post.reply
spring.cloud.stream.bindings.checkPostReply-in-0.group=auction-service

spring.cloud.stream.bindings.buyerDataRequest-out-0.destination=auction.buyer.data.request
spring.cloud.stream.bindings.buyerDataReply-in-0.destination=auction.buyer.data.reply
spring.cloud.stream.bindings.buyerDataReply-in-0.group=auction-service

spring.cloud.stream.bindings.postDataRequest-out-0.destination=auction.post.data.request
spring.cloud.stream.bindings.postDataReply-in-0.destination=auction.post.data.reply
spring.cloud.stream.bindings.postDataReply-in-0.group=auction-service

spring.cloud.stream.bindings.sendEmailOut-out-0.destination=auction.send.email

spring.cloud.stream.bindings.endedPostsRequest-out-0.destination=auction.ended.posts.request
spring.cloud.stream.bindings.endedPostsReply-in-0.destination=auction.ended.posts.reply
spring.cloud.stream.bindings.endedPostsReply-in-0.group=auction-service

spring.cloud.stream.bindings.updateBuyNowPriceRequest-out-0.destination=auction.update.buynowprice.request
spring.cloud.stream.bindings.updateBuyNowPriceReply-in-0.destination=auction.update.buynowprice.reply
spring.cloud.stream.bindings.updateBuyNowPriceReply-in-0.group=auction-service

spring.cloud.stream.bindings.endedPostDataRequest-out-0.destination=auction.ended.post.data.request
spring.cloud.stream.bindings.endedPostDataReply-in-0.destination=auction.ended.post.data.reply
spring.cloud.stream.bindings.endedPostDataReply-in-0.group=auction-service

# ArtworkPostServices input request
spring.cloud.stream.bindings.bidsDataFromPostRequest-in-0.destination=artworkpost.bids.data.request
spring.cloud.stream.bindings.bidsDataFromPostRequest-in-0.group=auction-service

# ArtworkPostServices output reply
spring.cloud.stream.bindings.bidsDataFromPostRequest-out-0.destination=artworkpost.bids.data.reply

# Register functions
spring.cloud.function.definition=checkBuyerReply;checkPostReply;buyerDataReply;postDataReply;endedPostsReply\
  ;updateBuyNowPriceReply;endedPostDataReply;bidsDataFromPostRequest

# Scheduler end point
management.endpoints.web.exposure.include=scheduledtasks